import {
  Activity,
  CalendarDays,
  CheckSquare,
  ClipboardList,
  Clock,
  FileEdit,
  FileText,
  Hash,
  Home,
  Inbox,
  LayoutDashboard,
  LayoutGrid,
  MessageSquare,
  MessageSquareReply,
  MessageSquareText,
  Presentation,
  ScrollText,
  Sparkles,
  Target,
  Users,
  type LucideIcon,
} from "lucide-react";

export const iconMapper: Record<string, LucideIcon> = {
  home: Home,
  spaces: LayoutGrid,
  chat: MessageSquare,
  planner: CalendarDays,
  ai: Sparkles,
  teams: Users,
  docs: FileText,
  dashboard: LayoutDashboard,
  whiteboard: Presentation,
  forms: ClipboardList,
  goals: Target,
  "time-sheets": Clock,
  inbox: Inbox,
  replies: MessageSquareReply,
  "assigned-comments": MessageSquareText,
  "my-tasks": CheckSquare,
  "chat-activity": Activity,
  drafts: FileEdit,
  posts: ScrollText,
  "all-channels": Hash,
  "all-spaces": LayoutGrid,
  "all-tasks": CheckSquare,
};
