export const ErrorMessages = {
  UNAUTHENTICATED: "Unauthenticated",
  UNAUTHORIZED: "Unauthorized",
  USER_NOT_FOUND: "User not found",
  MEMBER_NOT_FOUND: "Member not found",
  NOT_A_MEMBER: "Not a member",
  CANNOT_REMOVE_SELF: "You cannot remove yourself from the workspace",
  CANNOT_REMOVE_CREATOR: "The workspace creator cannot be removed",
  CANNOT_MODIFY_CREATOR: "The workspace creator's role cannot be changed",
  CANNOT_MODIFY_SELF: "You cannot change your own role",
  WORKSPACE_NOT_FOUND: "Workspace not found",
  NO_PERMISSION: "You do not have permission to perform this action",
  SPACE_NOT_FOUND: "Space not found",
  FAVOURITE_NOT_FOUND: "Favourite not found",
  ALREADY_FAVOURITED: "Item is already favourited",
  INVITATION_NOT_FOUND: "Invitation not found",
  INVITATION_EXPIRED: "This invitation has expired",
  INVITATION_ALREADY_ACCEPTED: "This invitation has already been accepted",
  INVITATION_CANCELLED: "This invitation has been cancelled",
  ALREADY_A_MEMBER: "You are already a member of this workspace",
} as const;
